/*
 * generated by Xtext
 */
package com.github.thomasfischl.kylang.test.ui.contentassist

import com.github.thomasfischl.kylang.test.ui.contentassist.AbstractTestLangProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class TestLangProposalProvider extends AbstractTestLangProposalProvider {
}
