/*
 * generated by Xtext
 */
package com.github.thomasfischl.kylang.test.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class TestLangUiModule extends com.github.thomasfischl.kylang.test.ui.AbstractTestLangUiModule {
  public TestLangUiModule(AbstractUIPlugin plugin) {
    super(plugin);
  }

  public Class<? extends org.eclipse.xtext.ui.editor.outline.IOutlineTreeProvider> bindIOutlineTreeProvider() {
    return com.github.thomasfischl.kylang.test.ui.outline.TestLangOutlineTreeProvider.class;
  }

  public Class<? extends org.eclipse.xtext.ui.editor.outline.impl.IOutlineTreeStructureProvider> bindIOutlineTreeStructureProvider() {
    return com.github.thomasfischl.kylang.test.ui.outline.TestLangOutlineTreeProvider.class;
  }

  @Override
  public Class<? extends org.eclipse.xtext.ui.editor.quickfix.IssueResolutionProvider> bindIssueResolutionProvider() {
    return com.github.thomasfischl.kylang.test.ui.quickfix.TestLangQuickfixProvider.class;
  }

  // public Class<? extends IHighlightingConfiguration> bindIHighlightingConfiguration() {
  // return TestLangHighlightingConfiguration.class;
  // }
  //
  // public Class<? extends ISemanticHighlightingCalculator> bindISemanticHighlightingCalculator() {
  // return TestLangHighlightingConfiguration.class;
  // }
}
