/*
 * generated by Xtext
 */
package com.github.thomasfischl.kylang.test.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class TestLangUiModule extends com.github.thomasfischl.kylang.test.ui.AbstractTestLangUiModule {
	public TestLangUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
