/*
 * generated by Xtext
 */
package com.github.thomasfischl.kylang.test;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class TestLangRuntimeModule extends com.github.thomasfischl.kylang.test.AbstractTestLangRuntimeModule {

}
